name: Display commit messages

on:
  push:

env:
  CI_SERVER: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: display_commit_messages
      run: |
          echo "commits: ${{toJSON(github.event.commits)}}"
          echo "head_commit: ${{toJSON(github.event.head_commit)}}" 

